// GENERATED by scripts/optimize-images.mjs. Do not edit by hand; run `npm run images`.

export type ImageCategory =
  | "exterior"
  | "pool"
  | "interior"
  | "bedroom"
  | "bbq"
  | "surroundings";

export interface GalleryImage {
  id: string;
  src: string;
  width: number;
  height: number;
  category: ImageCategory;
  blurDataURL: string;
}

export const heroImage = {
  src: "/images/hero.jpg",
  width: 1920,
  height: 1080,
  blurDataURL: "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQAgCdASoQAAwAA4BaJbACdH8AFkU9twzAAPyyrqH/rauCnYZA7im12BJPmfdtqRixwnLqLkibpHenSpRFVBzz2xQ5K2DCih7zlnAkdt/t45dgNvHBAIAA",
} as const;

export const aboutImageIds = ["exterior-02","exterior-03"] as const;

export const galleryImages: GalleryImage[] = [
  {
    "id": "pool-01",
    "src": "/images/pool-01.jpg",
    "width": 1600,
    "height": 1200,
    "category": "pool",
    "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAQCdASoQAAwAA4BaJZgCdADwGhuIhwAA/sXJvCrCewjwyh2RN0dRdnwhfZsZSQkeo1aYX0MGhqhvoSNqTpjtHwvqzbSjqTKqm61de54g89kNxWuGaaNQAAA="
  },
  {
    "id": "exterior-01",
    "src": "/images/exterior-01.jpg",
    "width": 1600,
    "height": 1200,
    "category": "exterior",
    "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoQAAwAA4BaJaACdAENpH9LAAD+6u085wVD47T5vldDyZMn6EBD76Jv4hY8acIcIPzoOHgLgBz7WZfSPQKt8j5g2oNNBcOvOsgAAA=="
  },
  {
    "id": "interior-01",
    "src": "/images/interior-01.jpg",
    "width": 1600,
    "height": 1200,
    "category": "interior",
    "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAwAgCdASoQAAwAA4BaJZACdAEWjf/+ptF/AAD+nCLr+d0zBF1DUmQkRkqZ62sXc0HgjLE/z9L/2uuJc8zSDnP+9IKQujRf+m8Li4iHQyP+WcmudPdiOdSrAT4AAA=="
  },
  {
    "id": "bbq-01",
    "src": "/images/bbq-01.jpg",
    "width": 1600,
    "height": 1200,
    "category": "bbq",
    "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAQAgCdASoQAAwAA4BaJaACdAEVlTl3gykAAPwlVwxJwOVc96OLtq13ji9HCRSiQQaODHhaXaTMW0MtZR3/CvGEFjZwTEArJTgHQowMHuiK/B2OW1Vwq/lfQ1sSxSqoAAA="
  },
  {
    "id": "bedroom-01",
    "src": "/images/bedroom-01.jpg",
    "width": 1600,
    "height": 1200,
    "category": "bedroom",
    "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoQAAwAA4BaJQBOgBUIvglY2YAA/t8M2GiHRYMWvuDUL9Gv9h/NDsk3gfCHVZcJWKuHPifWQxThDOmi33QirAYi6skHoZ8aXrCvBWrF26IAAA=="
  },
  {
    "id": "exterior-03",
    "src": "/images/exterior-03.jpg",
    "width": 1600,
    "height": 1200,
    "category": "exterior",
    "blurDataURL": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAABQAgCdASoQAAwAA4BaJZACdAEQ0qUd6jxltwAA/miforLauYL3yPh8PIOiqeejEs0Uh08B0gGWuR6vedNYXjOA/5sgkatJMWwBg3UEju7ERwbjm/zSnrjt/1UqUrJ321OSyFrW8QAAAA=="
  },
  {
    "id": "pool-03",
    "src": "/images/pool-03.jpg",
    "width": 1600,
    "height": 1200,
    "category": "pool",
    "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoQAAwAA4BaJQBdgBuVLxMKWAAA/rUeVOXZei7AqzfQpNSZhDq3nJLRCCnCyuLxIeiY/vSLH6ob+R7rI7Q4Rpl2FSlu4h+9/qAAAA=="
  },
  {
    "id": "interior-02",
    "src": "/images/interior-02.jpg",
    "width": 1600,
    "height": 1200,
    "category": "interior",
    "blurDataURL": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADwAQCdASoQAAwAA4BaJQBOgBjtEGe9GgAAzj4g8RcSFSr+OHy33QUtV0z1VvkqpejOSydeHeiI9TZ9ISm3rN5WPQaM88A+j3lpzWAUuwE806X1Kh902reH+jTAUtF0TOxjUYaXQjIAAA=="
  },
  {
    "id": "surroundings-02",
    "src": "/images/surroundings-02.jpg",
    "width": 1600,
    "height": 1200,
    "category": "surroundings",
    "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAQCdASoQAAwAA4BaJYwCw7EDST5TzAD+yM52E2sdc4zTK3zAs/AKmd423iHbd30oMWVfKh31iCP6TTslAOrxHIyu7HC8G/Ed9jgAYxS6AAAA"
  },
  {
    "id": "bedroom-02",
    "src": "/images/bedroom-02.jpg",
    "width": 1200,
    "height": 1600,
    "category": "bedroom",
    "blurDataURL": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JQBdgMYTbyR+ePO1KuY9ZMAD+eSmBTWynAxtX9bOuCGPlBuFeAV63LWD+jnmbrcWLSZCk8i3LKR/5QzAWOXgbSTBKivMd1ypLIdzzRTquRR5Tx47RQfI43uN9XFz0veVu/bpfb+s4TuWrLT5mH9oG6+jloAAA"
  },
  {
    "id": "bbq-03",
    "src": "/images/bbq-03.jpg",
    "width": 1600,
    "height": 1200,
    "category": "bbq",
    "blurDataURL": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAABwAgCdASoQAAwAA4BaJbACdH8AGYn/eLI050UAAP7tCvXFsLvSfzvi2JnQxtCYN3e6CfdErGbhfsl2ag5orDSfdlZOfKbk8KFU3TERkWw9xxfy5zbD97D9+U7Hi+5qLKpUsAAA"
  },
  {
    "id": "interior-03",
    "src": "/images/interior-03.jpg",
    "width": 1600,
    "height": 1200,
    "category": "interior",
    "blurDataURL": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADwAQCdASoQAAwAA4BaJZgCdAEDHcc820QA+p3qUQObuGvzsiL77XAkZcKqoX5ICNgOuChAnMUSExeyNtUSxXkWFfMOyjeAuytg7T2U69aYuOpTRN97CrrWjM7m3KKGGCNxZWGIAAA="
  },
  {
    "id": "exterior-02",
    "src": "/images/exterior-02.jpg",
    "width": 1600,
    "height": 1200,
    "category": "exterior",
    "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAwAgCdASoQAAwAA4BaJQBOgCK594oxl/L8gAD+sgsAj65p24oQ9tL+isF8vvH7fuSN1WK/fNquVjOk6ugTGjPtlB+TttMXjvnhyOfm+NX0XlKffACEDigiI6LckKO4PwAAAA=="
  },
  {
    "id": "pool-02",
    "src": "/images/pool-02.jpg",
    "width": 1600,
    "height": 1200,
    "category": "pool",
    "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAQCdASoQAAwAA4BaJYgCdACzPvxBoQgA/INF/1ospO2TkssNnaslrT7MIcg4HI/DI2f+tV97L4Cd9/sNJHY9UMYRKAWGf5/6ntY+XxqgCZF5Ydxf4liXDH1CPMgA"
  },
  {
    "id": "bedroom-03",
    "src": "/images/bedroom-03.jpg",
    "width": 1200,
    "height": 1600,
    "category": "bedroom",
    "blurDataURL": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAACwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JYgCdICY4ABhqOz6DkxTi/oeVB9sQAPjdVCAUMoMgX41lsFBHH1zRybzgZtAX6+mGZiRiOBFVAxnZ2lFwWCTDsnQKdGCJA0rSuvvP1WoYnmZr9R272KN8/y+k4apWxgP/9XeArNb5Wv5KAT1AAA=="
  },
  {
    "id": "interior-04",
    "src": "/images/interior-04.jpg",
    "width": 1200,
    "height": 1600,
    "category": "interior",
    "blurDataURL": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAADwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JQBOgBHwNkhgS00bm9ml4AP4l531o/4vb9dg5IiFLk6s37fnvAr0Dz/TLL8w79gnEK8OW2rTmHAgM+ez0RAuIE+8tpaYAPMdM/P6hrgtlld59Z5p1ZULAl7R80boukDeiWrq4yIu8YAAA"
  },
  {
    "id": "bbq-02",
    "src": "/images/bbq-02.jpg",
    "width": 1600,
    "height": 1200,
    "category": "bbq",
    "blurDataURL": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAACwAgCdASoQAAwAA4BaJbACdAYtz2Xr86Ugg7nziQAA/vXp1cgsONhZaoduIHOJBUrZxhRCFngGoHrKvo5/2+4hgvlAG22lOwg51TJd/7mTlR51FGB7GdUpWm7U/UTsqcEPAAAA"
  },
  {
    "id": "surroundings-01",
    "src": "/images/surroundings-01.jpg",
    "width": 1600,
    "height": 1200,
    "category": "surroundings",
    "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQAAwAA4BaJQBOgBtZCepBJiAA/luTK1K733aUZU0nsQ1Q1qSlKz2Ohwu0tT+97thYaOkbptR+6UOeeB+33sN+bi0tQ0Vx8TBA8JCGkLLP4AAA"
  },
  {
    "id": "exterior-04",
    "src": "/images/exterior-04.jpg",
    "width": 1600,
    "height": 1200,
    "category": "exterior",
    "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAQCdASoQAAwAA4BaJQBOgB06bvnN7KwA/u+Ks+uxDldAPthpd+K1z0dakDOWO/URgURfGsA4mUxcX8gIMMeIquRIjd2lGBxp2lx5J5v9CAAA"
  },
  {
    "id": "interior-05",
    "src": "/images/interior-05.jpg",
    "width": 1200,
    "height": 1600,
    "category": "interior",
    "blurDataURL": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZwAAaXztWDCqjFu+fIgeAACpUkEa+5il/hfXqDWYfLa6RMZuuVPD1VBMJaaHsBUiRwST9WdtNttSsWIWlzvB3CPCUJPTaZt1bhtZnbK+mbokNOBDWUFXivV04cWsO7iwcKcWgAA="
  },
  {
    "id": "pool-04",
    "src": "/images/pool-04.jpg",
    "width": 1600,
    "height": 1200,
    "category": "pool",
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQAgCdASoQAAwAA4BaJbACdAEO+4sIZmMAAP73e8Wp3jUpHR8q89QxGiFexUsNr4+rsPMDlyYphSAwIBa4ljaFO5Hx2zilAQd2rRQvQAA="
  }
];
