/**
 * Curated image pipeline: slike/ (raw WhatsApp exports) -> public/images/
 * plus a generated lib/image-manifest.ts with dimensions and blur placeholders.
 *
 * Curation decisions (category, keepers, hero) were made visually across all
 * 48 source photos; near-duplicates and low-quality shots are excluded.
 *
 * Run: npm run images
 */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const ROOT = path.resolve(import.meta.dirname, "..");
const SRC = path.join(ROOT, "slike");
const OUT = path.join(ROOT, "public", "images");

const W = (n) => `WhatsApp Image 2026-06-11 at ${n}.jpeg`;

/** Gallery keepers in display order (interleaved categories for rhythm). */
const GALLERY = [
  { src: W("17.48.23"), id: "pool-01", category: "pool" },
  { src: W("17.48.34"), id: "exterior-01", category: "exterior" },
  { src: W("17.48.50"), id: "interior-01", category: "interior" },
  { src: W("17.48.42"), id: "bbq-01", category: "bbq" },
  { src: W("17.48.51 (5)"), id: "bedroom-01", category: "bedroom" },
  { src: W("17.48.39"), id: "exterior-03", category: "exterior" },
  { src: W("17.48.35"), id: "pool-03", category: "pool" },
  { src: W("17.48.50 (2)"), id: "interior-02", category: "interior" },
  { src: W("17.48.44 (1)"), id: "surroundings-02", category: "surroundings" },
  { src: W("17.48.52 (1)"), id: "bedroom-02", category: "bedroom" },
  { src: W("17.48.52 (4)"), id: "bbq-03", category: "bbq" },
  { src: W("17.48.51 (2)"), id: "interior-03", category: "interior" },
  { src: W("17.48.36"), id: "exterior-02", category: "exterior" },
  { src: W("17.48.34 (1)"), id: "pool-02", category: "pool" },
  { src: W("17.48.46"), id: "bedroom-03", category: "bedroom" },
  { src: W("17.48.48 (3)"), id: "interior-04", category: "interior" },
  { src: W("17.48.44"), id: "bbq-02", category: "bbq" },
  { src: W("17.48.39 (1)"), id: "surroundings-01", category: "surroundings" },
  { src: W("17.48.45 (1)"), id: "exterior-04", category: "exterior" },
  { src: W("17.48.50 (4)"), id: "interior-05", category: "interior" },
  { src: W("17.48.53 (2)"), id: "pool-04", category: "pool" },
];

/** Best landscape shot: pool with stone facades, cypress, blue sky. */
const HERO_SRC = W("17.48.34 (2)");
/** Photos paired with the About/story section. */
const ABOUT_IDS = ["exterior-02", "exterior-03"];

async function blurDataURL(pipeline) {
  const buf = await pipeline.clone().resize(16).webp({ quality: 40 }).toBuffer();
  return `data:image/webp;base64,${buf.toString("base64")}`;
}

async function run() {
  await mkdir(OUT, { recursive: true });
  const manifest = [];

  for (const item of GALLERY) {
    const input = sharp(path.join(SRC, item.src)).rotate(); // bake EXIF orientation
    const resized = input.clone().resize(1600, 1600, { fit: "inside", withoutEnlargement: true });
    const outFile = path.join(OUT, `${item.id}.jpg`);
    const info = await resized.jpeg({ quality: 78, mozjpeg: true }).toFile(outFile);
    manifest.push({
      id: item.id,
      src: `/images/${item.id}.jpg`,
      width: info.width,
      height: info.height,
      category: item.category,
      blurDataURL: await blurDataURL(resized),
    });
    console.log(`gallery  ${item.id}.jpg  ${info.width}x${info.height}  ${(info.size / 1024).toFixed(0)} KB`);
  }

  // Hero: 1920w, gently cropped toward 16:9 for full-bleed use.
  const hero = sharp(path.join(SRC, HERO_SRC)).rotate();
  const heroResized = hero.clone().resize(1920, 1080, { fit: "cover", position: "attention" });
  const heroInfo = await heroResized.jpeg({ quality: 80, mozjpeg: true }).toFile(path.join(OUT, "hero.jpg"));
  const heroBlur = await blurDataURL(heroResized);
  console.log(`hero     hero.jpg  ${heroInfo.width}x${heroInfo.height}  ${(heroInfo.size / 1024).toFixed(0)} KB`);

  // OG: 1200x630 center crop of the same shot.
  await sharp(path.join(SRC, HERO_SRC))
    .rotate()
    .resize(1200, 630, { fit: "cover", position: "attention" })
    .jpeg({ quality: 80, mozjpeg: true })
    .toFile(path.join(ROOT, "public", "og.jpg"));
  console.log("og       og.jpg  1200x630");

  const ts = `// GENERATED by scripts/optimize-images.mjs. Do not edit by hand; run \`npm run images\`.

export type ImageCategory =
  | "exterior"
  | "pool"
  | "interior"
  | "bedroom"
  | "bbq"
  | "surroundings";

export interface GalleryImage {
  id: string;
  src: string;
  width: number;
  height: number;
  category: ImageCategory;
  blurDataURL: string;
}

export const heroImage = {
  src: "/images/hero.jpg",
  width: ${heroInfo.width},
  height: ${heroInfo.height},
  blurDataURL: "${heroBlur}",
} as const;

export const aboutImageIds = ${JSON.stringify(ABOUT_IDS)} as const;

export const galleryImages: GalleryImage[] = ${JSON.stringify(manifest, null, 2)};
`;
  await writeFile(path.join(ROOT, "lib", "image-manifest.ts"), ts);
  console.log(`manifest lib/image-manifest.ts (${manifest.length} gallery images)`);
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
